version: '3.8'

services:
  front:
    build: ../ecovoit_frontend
    volumes:
      - ../ecovoit_frontend/src:/app/src
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  api:
    build: ./
    environment:
      - PORT=4000
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
    depends_on:
      db :
        condition: service_healthy
    extra_hosts:
      # - "host.docker.internal:host-gateway"
      - "host.docker.internal:172.17.0.1"
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
    # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecovoit
    ports:
      - 5433:5432
    volumes:
      - ~/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5